### ISSUE TITLE
Support for xs:long

### ISSUE THREAD

**Issue by albertotn** [xmlet/XsdParser#2]
I'm facing an issue parsing an xsd with xs:long in restriction, here my xsd file:

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" id="PSS">
  <xs:simpleType name="IDContatto">
          <xs:restriction base="xs:long">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="99999999999999"/>
          </xs:restriction>
     </xs:simpleType>
</xs:schema>
```

Here the code:

```
package org.xmlet.xsdparser;

import java.util.List;
import java.util.stream.Collectors;

import org.junit.Test;
import org.xmlet.xsdparser.core.XsdParser;
import org.xmlet.xsdparser.xsdelements.XsdElement;

public class MyXsdTest {
	private static final String WPFE_FILE_NAME = HtmlParseTest.class.getClassLoader().getResource("longTest.xsd")
			.getPath();
	private static final List<XsdElement> elements;
	private static final XsdParser parser;

	static {
		parser = new XsdParser(WPFE_FILE_NAME);

		elements = parser.getParseResult().collect(Collectors.toList());
	}

	@Test
	public void testElementCount() {
		// Assert.assertEquals(89, elements.size());
	}
}
```

and the exception here:

```
java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.NumberFormatException: For input string: "99999999999999"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.xmlet.xsdparser.xsdelements.xsdrestrictions.XsdIntegerRestrictions.setFields(XsdIntegerRestrictions.java:34)
	at org.xmlet.xsdparser.xsdelements.XsdAbstractElement.<init>(XsdAbstractElement.java:71)
	at org.xmlet.xsdparser.xsdelements.XsdIdentifierElements.<init>(XsdIdentifierElements.java:19)
	at org.xmlet.xsdparser.xsdelements.XsdAnnotatedElements.<init>(XsdAnnotatedElements.java:21)
	at org.xmlet.xsdparser.xsdelements.xsdrestrictions.XsdIntegerRestrictions.<init>(XsdIntegerRestrictions.java:21)
	at org.xmlet.xsdparser.xsdelements.xsdrestrictions.XsdMaxInclusive.<init>(XsdMaxInclusive.java:23)
	at org.xmlet.xsdparser.xsdelements.xsdrestrictions.XsdMaxInclusive.parse(XsdMaxInclusive.java:33)
	at org.xmlet.xsdparser.xsdelements.XsdAbstractElement.xsdParseSkeleton(XsdAbstractElement.java:138)
	at org.xmlet.xsdparser.xsdelements.XsdRestriction.parse(XsdRestriction.java:133)
	at org.xmlet.xsdparser.xsdelements.XsdAbstractElement.xsdParseSkeleton(XsdAbstractElement.java:138)
	at org.xmlet.xsdparser.xsdelements.XsdSimpleType.parse(XsdSimpleType.java:106)
	at org.xmlet.xsdparser.xsdelements.XsdAbstractElement.xsdParseSkeleton(XsdAbstractElement.java:138)
	at org.xmlet.xsdparser.xsdelements.XsdSchema.parse(XsdSchema.java:114)
	at org.xmlet.xsdparser.core.XsdParser.parseFile(XsdParser.java:278)
	at org.xmlet.xsdparser.core.XsdParser.<init>(XsdParser.java:254)
	at org.xmlet.xsdparser.MyXsdTest.<clinit>(MyXsdTest.java:17)
	... 22 more
```

I saw that you consider all restrictions only as integer in the class XsdIntegerRestrictions , it's possible to consider also another numeric types, like long ?

**Comment by lcduarte** [comment]
I released a new version, 1.0.11 (https://github.com/xmlet/XsdParser/tree/xsdParser-1.0.11), that fixes the problems related with attribute types. 

In the case presented above the `value` attribute from `xsd:maxInclusive` and `xsd:minInclusive` should be a `Double`, which solves the problem. The remainder attributes from all XSD elements were all updated to respect the rules defined in the XSD syntax.

**Comment by albertotn** [comment]
Hi again! I've tried to use version 1.0.11 but in the junit above elements List is always empty

**Comment by lcduarte** [comment]
Keep in mind that the method `getParseResult` only returns `XsdElement` objects, which correspond to `xsd:element` elements. 

If you want to iterate on all the elements parsed by the `XsdParser` you should use the `getResultSchemas` which returns the `XsdSchema` objects which are the root of the XSD files and from there you can navigate to the `XsdSchema` children by invoking the `getXsdElements` method.

**Comment by albertotn** [comment]
Thanks! I think you could close this issue, well done!
